<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $page->product_name }} — Preview</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=inter:400,600,800&display=swap" rel="stylesheet" />
    <style>body{font-family:'Inter',sans-serif}</style>
</head>
<body class="bg-white text-slate-900">
@php($g = $page->generated_content)

<section class="bg-gradient-to-br from-indigo-600 to-violet-700 px-6 py-20 text-white">
    <div class="mx-auto max-w-4xl text-center">
        <p class="text-sm font-semibold uppercase tracking-widest text-indigo-200">{{ $g['subheadline'] ?? '' }}</p>
        <h1 class="mt-4 text-5xl font-extrabold leading-tight sm:text-6xl">{{ $g['headline'] ?? '' }}</h1>
        <p class="mx-auto mt-6 max-w-2xl text-lg text-indigo-100">{{ $g['description'] ?? '' }}</p>
        <a href="#cta" class="mt-8 inline-block rounded-full bg-white px-8 py-3 font-semibold text-indigo-700 shadow-lg hover:bg-indigo-50">{{ $g['call_to_action'] ?? 'Pesan Sekarang' }}</a>
    </div>
</section>

@if(!empty($g['benefits']))
<section class="px-6 py-16">
    <div class="mx-auto max-w-4xl">
        <h2 class="text-center text-3xl font-bold">Mengapa Memilih Kami</h2>
        <div class="mt-10 grid gap-6 sm:grid-cols-2">
            @foreach($g['benefits'] as $b)
                <div class="rounded-lg border bg-slate-50 p-5">
                    <p class="flex gap-3"><span class="text-emerald-500">✓</span><span>{{ $b }}</span></p>
                </div>
            @endforeach
        </div>
    </div>
</section>
@endif

@if(!empty($g['features']))
<section class="bg-slate-50 px-6 py-16">
    <div class="mx-auto max-w-4xl">
        <h2 class="text-center text-3xl font-bold">Fitur Utama</h2>
        <ul class="mx-auto mt-10 grid max-w-2xl gap-3 text-left">
            @foreach($g['features'] as $f)
                <li class="flex gap-3 rounded-lg bg-white p-4 shadow-sm"><span class="text-indigo-500">•</span><span>{{ $f }}</span></li>
            @endforeach
        </ul>
    </div>
</section>
@endif

@if(!empty($g['social_proof']))
<section class="px-6 py-16">
    <div class="mx-auto max-w-3xl text-center">
        <blockquote class="text-xl italic text-slate-700">"{{ $g['social_proof'] }}"</blockquote>
    </div>
</section>
@endif

<section id="cta" class="bg-indigo-50 px-6 py-20 text-center">
    <p class="text-4xl font-bold text-indigo-700">{{ $g['price'] ?? '' }}</p>
    <a href="#" class="mt-6 inline-block rounded-full bg-indigo-600 px-10 py-4 text-lg font-semibold text-white shadow-lg hover:bg-indigo-700">{{ $g['call_to_action'] ?? 'Pesan Sekarang' }}</a>
    <p class="mt-4 text-xs text-slate-500">Generated by AI Sales Page Generator · MCP-lite context engine</p>
</section>
</body>
</html>
